spring:

  profiles:
    active: local

  datasource:
    url: jdbc:postgresql://localhost:5432/chat
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create  # 필요에 따라 create, update, validate, none 중 선택
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
