spring:

  profiles:
    active: local

  datasource:
    url: jdbc:postgresql://localhost:5432/chat
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create  # 필요에 따라 create, update, validate, none 중 선택
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100

springdoc:
  swagger-ui:
    path: /docs/swagger-ui.html # UI 경로 변경
    enabled: true              # UI 활성화
    doc-expansion: list        # 초기 문서 펼침 설정
    operations-sorter: alpha   # API 정렬 방식
    persist-authorization: true # 로그인 후 세션 쿠키를 브라우저에 유지
  api-docs:
    path: /api-docs            # API 문서 경로 변경
    enabled: true              # API 문서 생성 활성화
  version: v3.0.1              # OpenAPI 스펙 버전 (선택 사항, Springdoc이 처리)